font = {
    "A": ["  X  ", " X X ", "XXXXX", "X   X", "X   X"],
    "B": ["XXXX ", "X   X", "XXXX ", "X   X", "XXXX "],
    "C": [" XXX ", "X   X", "X    ", "X   X", " XXX "],
    "D": ["XXXX ", "X   X", "X   X", "X   X", "XXXX "],
    "E": ["XXXXX", "X    ", "XXXX ", "X    ", "XXXXX"],
    "F": ["XXXXX", "X    ", "XXXX ", "X    ", "X    "],
    "G": [" XXX ", "X    ", "X XXX", "X   X", " XXX "],
    "H": ["X   X", "X   X", "XXXXX", "X   X", "X   X"],
    "I": [" XXX ", "  X  ", "  X  ", "  X  ", " XXX "],
    "J": ["  XXX", "   X ", "   X ", "X  X ", " XX  "],
    "K": ["X   X", "X  X ", "XXX  ", "X  X ", "X   X"],
    "L": ["X    ", "X    ", "X    ", "X    ", "XXXXX"],
    "M": ["X   X", "XX XX", "X X X", "X   X", "X   X"],
    "N": ["X   X", "XX  X", "X X X", "X  XX", "X   X"],
    "O": [" XXX ", "X   X", "X   X", "X   X", " XXX "],
    "P": ["XXXX ", "X   X", "XXXX ", "X    ", "X    "],
    "Q": [" XXX ", "X   X", "X   X", "X  XX", " XXXX"],
    "R": ["XXXX ", "X   X", "XXXX ", "X  X ", "X   X"],
    "S": [" XXXX", "X    ", " XXX ", "    X", "XXXX "],
    "T": ["XXXXX", "  X  ", "  X  ", "  X  ", "  X  "],
    "U": ["X   X", "X   X", "X   X", "X   X", " XXX "],
    "V": ["X   X", "X   X", "X   X", " X X ", "  X  "],
    "W": ["X   X", "X   X", "X X X", "XX XX", "X   X"],
    "X": ["X   X", " X X ", "  X  ", " X X ", "X   X"],
    "Y": ["X   X", " X X ", "  X  ", "  X  ", "  X  "],
    "Z": ["XXXXX", "   X ", "  X  ", " X   ", "XXXXX"],
    "0": [" XXX ", "X  XX", "X X X", "XX  X", " XXX "],
    "1": ["  X  ", " XX  ", "  X  ", "  X  ", " XXX "],
    "2": [" XXX ", "X   X", "   X ", "  X  ", "XXXXX"],
    "3": ["XXXXX", "   X ", " XXX ", "   X ", "XXXXX"],
    "4": ["X   X", "X   X", "XXXXX", "    X", "    X"],
    "5": ["XXXXX", "X    ", "XXXX ", "    X", "XXXX "],
    "6": [" XXX ", "X    ", "XXXX ", "X   X", " XXX "],
    "7": ["XXXXX", "   X ", "  X  ", " X   ", "X    "],
    "8": [" XXX ", "X   X", " XXX ", "X   X", " XXX "],
    "9": [" XXX ", "X   X", " XXXX", "    X", " XXX "],
    " ": ["     ", "     ", "     ", "     ", "     "],  # space
}
